FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["Gozon.Orders/Gozon.Orders.Api/Gozon.Orders.Api.csproj", "Gozon.Orders/Gozon.Orders.Api/"]
COPY ["Gozon.Shared/Gozon.Shared/Gozon.Shared.csproj", "Gozon.Shared/Gozon.Shared/"]

RUN dotnet restore "Gozon.Orders/Gozon.Orders.Api/Gozon.Orders.Api.csproj"

COPY . .

WORKDIR "/src/Gozon.Orders/Gozon.Orders.Api"
RUN dotnet build "Gozon.Orders.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Gozon.Orders.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 8080
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Gozon.Orders.Api.dll"]
